// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOhk_5EyQAoOt6l6FD12T9auXjyoaRWM',
    appId: '1:999374962386:web:8f5ed115f6ce84241b770b',
    messagingSenderId: '999374962386',
    projectId: 'fir-d952a',
    authDomain: 'fir-d952a.firebaseapp.com',
    storageBucket: 'fir-d952a.appspot.com',
    measurementId: 'G-KTG4EVRNVP',
    databaseURL:'https://fir-d952a-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5UBhY0X5b7LIQuS11msA8rYTGSxf1qag',
    appId: '1:999374962386:android:dfa5876166a40ffa1b770b',
    messagingSenderId: '999374962386',
    projectId: 'fir-d952a',
    storageBucket: 'fir-d952a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqy-znDeQHlEE9AxoITMbxFwsrKfnthus',
    appId: '1:999374962386:ios:3c0af7c58c3abedf1b770b',
    messagingSenderId: '999374962386',
    projectId: 'fir-d952a',
    storageBucket: 'fir-d952a.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqy-znDeQHlEE9AxoITMbxFwsrKfnthus',
    appId: '1:999374962386:ios:fcb6895dc30525621b770b',
    messagingSenderId: '999374962386',
    projectId: 'fir-d952a',
    storageBucket: 'fir-d952a.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
